# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NMFRandomiz.ui'
#
# Created: Sat Aug  6 18:46:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 623)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_widget = QtGui.QWidget(self.centralwidget)
        self.left_widget.setGeometry(QtCore.QRect(0, 0, 191, 551))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_widget.sizePolicy().hasHeightForWidth())
        self.left_widget.setSizePolicy(sizePolicy)
        self.left_widget.setObjectName("left_widget")
        self.widget_3 = QtGui.QWidget(self.left_widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 191, 551))
        self.widget_3.setObjectName("widget_3")
        self.randomizK_cb = QtGui.QCheckBox(self.widget_3)
        self.randomizK_cb.setGeometry(QtCore.QRect(10, 150, 97, 30))
        self.randomizK_cb.setObjectName("randomizK_cb")
        self.load_btn = QtGui.QToolButton(self.widget_3)
        self.load_btn.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.load_btn.setObjectName("load_btn")
        self.num_comps_input_text = QtGui.QLineEdit(self.widget_3)
        self.num_comps_input_text.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.num_comps_input_text.setObjectName("num_comps_input_text")
        self.randomizfreq_cb = QtGui.QCheckBox(self.widget_3)
        self.randomizfreq_cb.setGeometry(QtCore.QRect(10, 170, 161, 30))
        self.randomizfreq_cb.setObjectName("randomizfreq_cb")
        self.randomiztime_cb = QtGui.QCheckBox(self.widget_3)
        self.randomiztime_cb.setGeometry(QtCore.QRect(10, 190, 161, 30))
        self.randomiztime_cb.setObjectName("randomiztime_cb")
        self.computenmf_btn = QtGui.QToolButton(self.widget_3)
        self.computenmf_btn.setGeometry(QtCore.QRect(10, 240, 161, 41))
        self.computenmf_btn.setObjectName("computenmf_btn")
        self.num_comps_title = QtGui.QLabel(self.widget_3)
        self.num_comps_title.setGeometry(QtCore.QRect(10, 60, 161, 31))
        self.num_comps_title.setObjectName("num_comps_title")
        self.mode_custom_title = QtGui.QLabel(self.widget_3)
        self.mode_custom_title.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.mode_custom_title.setObjectName("mode_custom_title")
        self.right_widget = QtGui.QWidget(self.centralwidget)
        self.right_widget.setGeometry(QtCore.QRect(189, 0, 811, 551))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_widget.sizePolicy().hasHeightForWidth())
        self.right_widget.setSizePolicy(sizePolicy)
        self.right_widget.setObjectName("right_widget")
        self.widget_4 = QtGui.QWidget(self.right_widget)
        self.widget_4.setGeometry(QtCore.QRect(0, 490, 811, 101))
        self.widget_4.setObjectName("widget_4")
        self.playback_widget = QtGui.QWidget(self.widget_4)
        self.playback_widget.setGeometry(QtCore.QRect(460, 0, 351, 61))
        self.playback_widget.setObjectName("playback_widget")
        self.stop_btn = QtGui.QToolButton(self.playback_widget)
        self.stop_btn.setGeometry(QtCore.QRect(240, 10, 41, 41))
        self.stop_btn.setObjectName("stop_btn")
        self.play_btn = QtGui.QToolButton(self.playback_widget)
        self.play_btn.setGeometry(QtCore.QRect(180, 10, 41, 41))
        self.play_btn.setObjectName("play_btn")
        self.save_btn = QtGui.QToolButton(self.playback_widget)
        self.save_btn.setGeometry(QtCore.QRect(300, 10, 41, 41))
        self.save_btn.setObjectName("save_btn")
        self.navigation_widget = QtGui.QWidget(self.widget_4)
        self.navigation_widget.setGeometry(QtCore.QRect(10, 0, 361, 61))
        self.navigation_widget.setObjectName("navigation_widget")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.navigation_widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.navigation_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.navigation_layout.setContentsMargins(0, 0, 0, 0)
        self.navigation_layout.setObjectName("navigation_layout")
        self.figure_widget = QtGui.QWidget(self.right_widget)
        self.figure_widget.setGeometry(QtCore.QRect(-1, 9, 811, 481))
        self.figure_widget.setObjectName("figure_widget")
        self.verticalLayoutWidget = QtGui.QWidget(self.figure_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 801, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.figure_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.figure_layout.setContentsMargins(0, 0, 0, 0)
        self.figure_layout.setObjectName("figure_layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 22))
        self.menubar.setObjectName("menubar")
        self.menuNMF_Randomiz = QtGui.QMenu(self.menubar)
        self.menuNMF_Randomiz.setObjectName("menuNMF_Randomiz")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuNMF_Randomiz.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.randomizK_cb.setText(QtGui.QApplication.translate("MainWindow", "randomiz K", None, QtGui.QApplication.UnicodeUTF8))
        self.load_btn.setText(QtGui.QApplication.translate("MainWindow", "load audio", None, QtGui.QApplication.UnicodeUTF8))
        self.randomizfreq_cb.setText(QtGui.QApplication.translate("MainWindow", "randomiz frequencies", None, QtGui.QApplication.UnicodeUTF8))
        self.randomiztime_cb.setText(QtGui.QApplication.translate("MainWindow", "randomiz time", None, QtGui.QApplication.UnicodeUTF8))
        self.computenmf_btn.setText(QtGui.QApplication.translate("MainWindow", "compute NMF", None, QtGui.QApplication.UnicodeUTF8))
        self.num_comps_title.setText(QtGui.QApplication.translate("MainWindow", "num components:", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_custom_title.setText(QtGui.QApplication.translate("MainWindow", "custom mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_btn.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.play_btn.setText(QtGui.QApplication.translate("MainWindow", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNMF_Randomiz.setTitle(QtGui.QApplication.translate("MainWindow", "NMF Randomiz", None, QtGui.QApplication.UnicodeUTF8))

